Install node version 11.5.0 in trailofbits/eth-sec-toolbox (#722)
That docker image comes with node v12, but many core node modules
(including keccak) aren't compatible with node v12.

I needed to make two additional changes:

1. Blow away the cache for Slither and Echidna
2. Claim ownership of another directory when running Slither. Otherwise, we get this error:
```
Error: EACCES: permission denied, open '/home/ethsec/.config/truffle/config.json'
You don't have access to this file.
```

Signed-off-by: Prasad Tare prasad.tare@gmail.com